name: "Django Test CI Python 2.7"
description: "A github action to run your django tests in Python 2.7"
branding:
  icon: check-circle
  color: green
inputs:
  settings-dir-path:
    description: "The path of the directory containing the settings file(Without `./`)"
    required: true
  parallel-tests:
    description: "Run tests in parallel"
    default: false
    required: false
  requirements-file:
    description: "The path of dependancy file, typically requirements.txt"
    default: "requirements.txt"
    required: false
  env-file:
    description: "The path of an env file, if you require environment variables"
    default: ""
    required: false
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.settings-dir-path }}
    - ${{ inputs.parallel-tests }}
    - ${{ inputs.requirements-file }}
    - ${{ inputs.env-file }}
